id: opecha:P001827
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG9290
  title: མྱོས་བྱེད་ཀྱི་བཏུང་བའི་ཉེས་དམིགས་མདོ་རྒྱུད་བསྟན་བཅོས་རྣམས་ལས་བཏུས་པ་ཉེས་པའི་འཕྲང་སྒྲོལ།
  volume: ''
  author: ''
